// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// CLEAR error
export const CLEAR_ERROR_REQUEST = 'CLEAR_ERROR_REQUEST';
export const CLEAR_ERROR_SUCCESS = 'CLEAR_ERROR_SUCCESS';
export const CLEAR_ERROR_FAILURE = 'CLEAR_ERROR_FAILURE';

// USER LOADING
export const USER_LOADING_REQUEST = 'USER_LOADING_REQUEST';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAILURE = 'USER_LOADING_FAILURE';

// ToMeQuestion
export const TOME_REQUEST = 'TOME_REQUEST';
export const TOME_SUCCESS = 'TOME_SUCCESS';
export const TOME_FAILURE = 'TOME_FAILURE';

// ToMeAnswerReceive
export const TOME_ANSWER_RECEIVE_REQUEST = 'TOME_ANSWER_RECEIVE_REQUEST';
export const TOME_ANSWER_RECEIVE_SUCCESS = 'TOME_ANSWER_RECEIVE_SUCCESS';
export const TOME_ANSWER_RECEIVE_FAILURE = 'TOME_ANSWER_RECEIVE_FAILURE';

// BYOTHER DETAIL LOADING
export const BYOTHER_DETAIL_LOADING_REQUEST = 'BYOTHER_DETAIL_LOADING_REQUEST';
export const BYOTHER_DETAIL_LOADING_SUCCESS = 'BYOTHER_DETAIL_LOADING_SUCCESS';
export const BYOTHER_DETAIL_LOADING_FAILURE = 'BYOTHER_DETAIL_LOADING_FAILURE';

// BYOTHER ANSWER LOADING
export const BYOTHER_ANSWER_LOADING_REQUEST = 'BYOTHER_ANSWER_LOADING_REQUEST';
export const BYOTHER_ANSWER_LOADING_SUCCESS = 'BYOTHER_ANSWER_LOADING_SUCCESS';
export const BYOTHER_ANSWER_LOADING_FAILURE = 'BYOTHER_ANSWER_LOADING_FAILURE';

// BYOTHER_UPLOAD_REQUEST
export const BYOTHER_UPLOAD_REQUEST = 'BYOTHER_UPLOAD_REQUEST';
export const BYOTHER_UPLOAD_SUCCESS = 'BYOTHER_UPLOAD_SUCCESS';
export const BYOTHER_UPLOAD_FAILURE = 'BYOTHER_UPLOAD_FAILURE';

// ToMeAnswerUpload
export const TOME_ANSWER_UPLOAD_REQUEST = 'TOME_ANSWER_UPLOAD_REQUEST';
export const TOME_ANSWER_UPLOAD_SUCCESS = 'TOME_ANSWER_UPLOAD_SUCCESS';
export const TOME_ANSWER_UPLOAD_FAILURE = 'TOME_ANSWER_UPLOAD_FAILURE';

// ToMeInit
export const TOME_INIT = 'TOME_INIT';

// ReflQuestion
export const REFL_REQUEST = 'REFL_REQUEST';
export const REFL_SUCCESS = 'REFL_SUCCESS';
export const REFL_FAILURE = 'REFL_FAILURE';

// ReflAnswerReceive
export const REFL_ANSWER_RECEIVE_REQUEST = 'REFL_ANSWER_RECEIVE_REQUEST';
export const REFL_ANSWER_RECEIVE_SUCCESS = 'REFL_ANSWER_RECEIVE_SUCCESS';
export const REFL_ANSWER_RECEIVE_FAILURE = 'REFL_ANSWER_RECEIVE_FAILURE';

// ReflAnswerUpload
export const REFL_ANSWER_UPLOAD_REQUEST = 'REFL_ANSWER_UPLOAD_REQUEST';
export const REFL_ANSWER_UPLOAD_SUCCESS = 'REFL_ANSWER_UPLOAD_SUCCESS';
export const REFL_ANSWER_UPLOAD_FAILURE = 'REFL_ANSWER_UPLOAD_FAILURE';

// ReflInit
export const REFL_INIT = 'REFL_INIT';

// MyAccountReceive
export const MYAC_RECEIVE_REQUEST = 'MYAC_RECEIVE_REQUEST';
export const MYAC_RECEIVE_SUCCESS = 'MYAC_RECEIVE_SUCCESS';
export const MYAC_RECEIVE_FAILURE = 'MYAC_RECEIVE_FAILURE';
